# MAILSENDER DIRECTORY
#TRANSFER.ROOT.DIR=D:\\MPv3_engine\\Neocast@Messager\\
TRANSFER.ROOT.DIR=./
TRANSFER.REPOSITORY.DIR=repository/transfer/

<<<<<<< sender.properties

#SEND.IP�� SEND.DOMAIN�� �ּ��� ���̰ų�
#������ ������ java.lang.NullPointerException�� ����.
#SEND.IP=10.187.28.175
SEND.IP=192.168.0.7
SEND.DOMAIN=enders.co.kr

#DNS 
#NAME.SERVER=219.250.36.130
NAME.SERVER=168.126.63.1

#Transfer Agent Set
# Available Amount of Thread[default = 100]
MESSAGE.SENDER.AGENT=15

#Retry Set
# Retry Amount of Thread[default = 50]
RETRY.SENDER.AGENT=10

### Caution Fixed Value ( You shouldn't modify below lines) ###
GENERATOR.IP=127.0.0.1
GENERATOR.PORT=13107

# defalut Socket timeout = 20000(20sec)
SEND.BUFFER=4096
READ.BUFFER=2048

# Retry Delay Time(ms)
RETRY.WAIT.TIME=500

#Log Delete Period [day, week, month]
#Day
DELETE.PERIOD=86400000  
#Week
#DELETE.PERIOD=604800000
#Month
#DELETE.PERIOD=2592000000

#Insert Module's ENV
INSERT.PERIOD=120

# TLS 관련 설정
# 적용 도메인, 도메인이 여러개일 경우 콤마(,)로 구분
TLS.target.domain=gmail.com,yahoo.co.kr
TLS.version=TLSv1.2
